# Generated by Django 2.0.4 on 2018-07-08 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester'), (8, '8th semester')], verbose_name='Semester NO')),
                ('course_no', models.CharField(max_length=100, verbose_name='Course No')),
                ('course_title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('credit', models.CharField(max_length=100, verbose_name='Credit')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField(choices=[(1, '1st semester'), (2, '2nd semester'), (3, '3rd semester'), (4, '4th semester'), (5, '5th semester'), (6, '6th semester'), (7, '7th semester'), (8, '8th semester')], verbose_name='Semester NO')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(verbose_name='Roll NO')),
                ('registration_no', models.IntegerField(verbose_name='Registration NO')),
                ('session', models.CharField(max_length=10, null=True, verbose_name='Session')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='accounts.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_no', 'student')},
        ),
    ]
